name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install nightly toolchain
      run: rustup toolchain add nightly
    - name: Set default toolchain to stable
      run: rustup default stable
    - name: Update stable toolchain
      run: rustup update stable
    - name: Install miri
      run: rustup component add --toolchain nightly miri
    - name: Build
      run: cargo test --verbose
    - name: Run tests with valgrind
      run: sudo apt install -y valgrind && cargo install cargo-valgrind && cargo valgrind test --verbose
    - name: Run tests in Miri
      run: cargo +nightly miri test
